import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { ProductVisual } from "@/components/store/product-visual";
import { Button } from "@/components/ui/button";
import { addCartItemFormAction } from "@/features/cart/actions/cart";
import { getProductBySlug } from "@/features/storefront/services/storefront-service";
import { formatMoney } from "@/lib/utils/money";
import { siteConfig } from "@/config/site";

export async function generateMetadata({ params }: PageProps<"/shop/[slug]">): Promise<Metadata> { const { slug }=await params; const product=await getProductBySlug(slug); if(!product)return {title:"Fragrance not found"}; return {title:product.seo_title ?? product.name,description:product.seo_description ?? product.description.slice(0,160)}; }

export default async function ProductPage({ params }: PageProps<"/shop/[slug]">) {
  const { slug }=await params; const product=await getProductBySlug(slug); if(!product)notFound(); const first=product.variants[0];
  const jsonLd={"@context":"https://schema.org","@type":"Product",name:product.name,description:product.description,brand:{"@type":"Brand",name:product.brand.name},offers:product.variants.map(v=>({"@type":"Offer",price:v.price_minor/100,priceCurrency:v.currency,availability:"https://schema.org/InStock",url:`${siteConfig.url}/shop/${product.slug}`}))};
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd).replace(/</g,"\\u003c")}}/><div className="mx-auto grid max-w-[90rem] gap-12 px-5 py-12 sm:px-8 lg:grid-cols-2 lg:px-12 lg:py-20"><ProductVisual className="lg:sticky lg:top-36" label={product.name.slice(0,12)}/><div className="py-4 lg:px-8"><p className="text-xs tracking-[0.2em] text-gold uppercase">{product.brand.name} · {product.concentration}</p><h1 className="mt-4 font-display text-6xl leading-none">{product.name}</h1>{product.subtitle?<p className="mt-4 text-lg text-muted">{product.subtitle}</p>:null}<p className="mt-8 leading-8 text-muted">{product.description}</p>{first?<form action={addCartItemFormAction} className="mt-10 space-y-5"><fieldset><legend className="mb-3 text-xs font-semibold tracking-[0.12em] uppercase">Choose your size</legend><div className="flex flex-wrap gap-3">{product.variants.map((v,i)=><label key={v.id} className="cursor-pointer border px-5 py-3 has-[:checked]:border-charcoal has-[:checked]:bg-charcoal has-[:checked]:text-pearl"><input className="sr-only" type="radio" name="variantId" value={v.id} defaultChecked={i===0}/><span className="text-sm">{v.label} · {formatMoney(v.price_minor,v.currency)}</span></label>)}</div></fieldset><input type="hidden" name="quantity" value="1"/><Button className="w-full" type="submit">Add to bag</Button></form>:<p className="mt-10 border p-5 text-sm text-muted">This composition is currently unavailable.</p>}<dl className="mt-12 grid grid-cols-2 gap-6 border-t pt-8 text-sm"><div><dt className="text-muted">Longevity</dt><dd className="mt-1">{product.longevity_hours_min ?? "—"}–{product.longevity_hours_max ?? "—"} hours</dd></div><div><dt className="text-muted">Sillage</dt><dd className="mt-1 capitalize">{product.sillage ?? "—"}</dd></div><div><dt className="text-muted">Perfumer</dt><dd className="mt-1">{product.perfumer ?? "Undisclosed"}</dd></div><div><dt className="text-muted">Launch year</dt><dd className="mt-1">{product.launch_year ?? "—"}</dd></div></dl>{product.story?<div className="mt-12 border-t pt-8"><h2 className="font-display text-3xl">The story</h2><p className="mt-4 leading-8 text-muted">{product.story}</p></div>:null}</div></div></>;
}
